# Introduction to NumPy - Part 1

In [2]:
import numpy as np

Numpy Arrays

In [3]:
# Creating 1D arrays (Vectors)
vector = np.array([1, 2, 3, 4, 5])
print("Vector:\n", vector)
print("Shape:", vector.shape)
print("Data Type:", vector.dtype)

# Creating 2D arrays (Matrices)
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print("\nMatrix:\n", matrix)
print("Shape:", matrix.shape)

# Creating higher-dimensional arrays (Tensors)
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nTensor:\n", tensor)
print("Shape:", tensor.shape) # (2, 2, 2) - Think of it as 2 matrices of 2x2

Vector:
 [1 2 3 4 5]
Shape: (5,)
Data Type: int64

Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)

Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


### Zeros, Ones and Random Array

In [4]:
zeros = np.zeros((2, 3))
print("\nZeros:\n", zeros)

ones = np.ones((3, 2))
print("\nOnes:\n", ones)

random_numbers = np.random.rand(2, 2) # Values between 0 and 1
print("\nRandom:\n", random_numbers)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Random:
 [[0.67964365 0.46048413]
 [0.30381017 0.83979285]]


Reshaping and Broadcasting!